apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  type: NodePort
  selector:
    app: pgsql
  ports:
   - name: psqlport
     port: 5432
     targetPort: 5432
     nodePort: 30543
     protocol: TCP
