apiVersion: v1
kind: Service
metadata:
  name: zabbix-db-nodeport
  labels:
    app: zabbix
    tier: database
spec:
  type: NodePort
  selector:
    name: zabbix-db
  ports:
   - name: pgsqlport
     port: 5432
     targetPort: 5432
     nodePort: 30543
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: database
spec:
  type: ClusterIP
  selector:
    name: zabbix-db
  ports:
   - name: pgsqlport
     port: 5432
     targetPort: 5432
     protocol: TCP

