apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql-dbms
spec:
  serviceName: pgsql-svc
  selector:
    matchLabels:
      app: pgsql
  replicas: 2
  # Estrategia a la hora de aplicar este manifiesto
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql-dbms
          image: postgres:9.6
          imagePullPolicy: "IfNotPresent"
          # Limites de recursos por pod
          resources:
            limits:
              cpu: 400m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
          # Puerto a exponer del contenedor
          ports:
            - containerPort: 5432
          # Hacer referencia a secrets para importar variables
          env:
          - name: POSTGRES_DB
            value: testingdb
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pgsql-secret-values
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:    
              secretKeyRef:
                name: pgsql-secret-values
                key: POSTGRES_PASSWORD
          # Crea el punto de montaje postgresql-data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgsql-data
              readOnly: false
            # Usar configmap para enviar archivos de configuración a los pods mediante un volumen (se pueden copiar automaticamente a data/ usando un pod custom con initContainer)
            - mountPath: /opt/custom-postgresql-conf
              name: custom-postgresql-conf
      # Asigna el PVC que hara referencia al punto de montaje en el contenedor
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-pv-claim
        - name: custom-postgresql-conf
          configMap:
            name: custom-postgresql-configmap
