apiVersion: v1
kind: PersistentVolume
# Volumen fisico en el host que almacena datos persistentes
metadata:
  name: pgsql-pv-templatesdb
  labels:
    type: local
spec:
  # Vincular el PV al PVC específico para que solo pueda ser reclamado por este
  claimRef:
    name: pgsql-pv-templatesdb-claim
    namespace: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/srv/postgresql-db/disk/config"

---

apiVersion: v1
kind: PersistentVolumeClaim
# Solicitud de PV, con las características que se indican en "spec:"
metadata:
  name: pgsql-pv-templatesdb-claim
spec:
  volumeName: pgsql-pv-templatesdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# Volumes flux: Pod -> PVC -> PV -> Host machine
