apiVersion: v1
kind: Service
metadata:
  name: pgsql-clusterip
  labels:
    app: pgsql
spec:
  type: ClusterIP
  clusterIP: 10.152.183.100
  selector:
    app: pgsql
  ports:
   - name: pgsqlport
     port: 5432
     targetPort: 5432
     protocol: TCP
