apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret-values
type: Opaque
# Usar "data:" si se van a pasar cadenas codificadas en base64
stringData:
  pgsql-root-pwd: cGFzc3s%cmQ=
  username: postgres
