apiVersion: v1
kind: Service
metadata:
  name: zproxy-sqlite
  labels:
    app: zabbix
    tier: proxy
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zproxy-sqlite
  sessionAffinity: None

--

apiVersion: v1
kind: Service
metadata:
  name: zproxy-sqlite-nodeport
  labels:
    app: zabbix
    tier: proxy
spec:
  type: NodePort
  selector:
    name: zproxy-sqlite
  ports:
   - name: snmp-trap
     port: 1162
     targetPort: 1162
     nodePort: 300162
     protocol: TCP
