apiVersion: v1
kind: ConfigMap
metadata:
  name: zproxy-sqlite-env
  labels:
    app: zabbix
    tier: proxy
data:
  ZBX_PROXYMODE: "1" # active proxy
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  ZBX_HOSTNAME: "zproxy-sqlite"
  ZBX_DEBUGLEVEL: "3"
#  ZBX_LOADMODULE: "example1.so,example2.so"
#  ZBX_TIMEOUT: ""
  ZBX_JAVAGATEWAY_ENABLE: "true"
  DEBUG_MODE: "false"
