apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-web-env
  labels:
    app: zabbix-web
data:
  ZBX_SERVER_HOST: "10.152.183.77"
  ZBX_SERVER_PORT: "10051"
  DB_SERVER_PORT: "5432"
  DB_SERVER_HOST: "10.152.183.100"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "Secret*1313"
  POSTGRES_DB: "zabbix"
  TZ: "Europe/Madrid"
  PHP_TZ: "Europe/Madrid" 
