apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  ports:
  - name: port-trapper
    port: 10051
    protocol: TCP
    targetPort: 10051
  - name: port-agent
    port:  10050
    protocol: TCP
    targetPort: 10050

  selector:
    name: zabbix-server
