apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:5.4.2-alpine
        imagePullPolicy: IfNotPresent
        # Usar root, no recomendable para producción
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 80
          name: webport
          protocol: TCP
        # Se usa envFrom para configurar TODOS los datos de ConfigMap como variables del contenedor
        envFrom:
        - configMapRef:
            name: zabbix-web-env
