apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080
    targetPort: 8080
  selector:
    name: zabbix-web
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: zabbix-web