apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-nodeport
  labels:
    app: zabbix
    tier: web
spec:
  type: NodePort
  selector:
    name: zabbix-web
  ports:
   - name: web-http
     port: 8080
     targetPort: 8080
     nodePort: 30080
     protocol: TCP
---     
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: zabbix-web

