apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-env
  labels:
    app: zabbix-agent
data:
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  ZBX_PASSIVE_ALLOW: "true"
  ZBX_STARTAGENTS: "3"
  ZBX_TIMEOUT: "10"
