apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
        tier: web
    spec:
      initContainers:
      - name: performance-tunning
        image: busybox:1.34
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/sh
        - -c
        - |
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.ipv4.ip_local_port_range="1024 65535"
            sysctl -w net.ipv4.conf.all.accept_redirects=0
            sysctl -w net.ipv4.conf.all.secure_redirects=0
            sysctl -w net.ipv4.conf.all.send_redirects=0
        securityContext:
          privileged: true
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-5.4-latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          #allowPrivilegeEscalation: false
          #runAsUser: 0
        ports:
        - containerPort: 8080
          name: web-http
        - containerPort: 8443
          name: web-https
        resources:
            limits:
              cpu: 700m
              memory: "512M"
            requests:
              cpu: 500m
              memory: "256M"
        livenessProbe:
          httpGet:
            path: /
            port: web-http
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        # Se usa envFrom para configurar TODOS los datos de ConfigMap como variables del contenedor
        envFrom:
        - configMapRef:
            name: zabbix-web-env
      terminationGracePeriodSeconds: 10
