apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:5.4.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            name: server
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: server
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: server
            initialDelaySeconds: 15
            periodSeconds: 20
          # Se usa envFrom para configurar TODOS los datos de ConfigMap como variables del contenedor
          envFrom:
          - configMapRef:
              name: zabbix-server-env
        - name: zabbix-agent
          image: zabbix/zabbix-agent:5.4.2-alpine
          imagePullPolicy: Always
          ports:
          - containerPort: 10050
            name: zabbix-agent
          envFrom:
          - configMapRef:
              name: zabbix-agent-env
          securityContext:
            privileged: true
