apiVersion: v1
kind: Service
metadata:
  name: zabbixserver
spec:
  type: ClusterIP
  clusterIP: 10.152.183.77
  ports:
  - port:  10051
    protocol: TCP
    targetPort: 10051
  selector:
    app: zabbix-server
