apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: zabbix-web
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: pgsql-dbms
  selector:
    name: pgsql-dbms
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - name: zagentport
    port:  10050
    protocol: TCP
    targetPort: 10050

  selector:
    name: zabbix-server
